version: "3.9"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    project:
        build: .
        command: >
            sh -c "python manage.py makemigrations && 
                   python manage.py migrate &&
                   python manage.py collectstatic --noinput &&
                   python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - ./.env
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASS=postgres